on: push
name: Audit and Publish
jobs:
  auditAndPublish:
    name: Audit and Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      uses: felixbrucker/npm@master
      with:
        args: ci
    - name: Audit dependencies
      uses: felixbrucker/npm@master
      with:
        args: audit --production
    - name: Publish to npm
      if: startsWith(github.ref, 'refs/tags/')
      uses: felixbrucker/npm@master
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      with:
        args: publish --access public
